@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package cn.nulladev.technicalcores;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;